obstacle_range: 0.8
raytrace_range: 8.5
footprintL: [[0.3,0.14],[0.3,0.14],[0.3,0.14],[0.3,0.14]]
map_topic: /map
subscribe_to_update: true
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: scan, marking: true, claering: true}
global_frame: map
robot_base_frame: base_link
always_send_full_costmap: true